# Generated by Django 5.0.6 on 2024-07-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0004_users_added_by_user_id_alter_users_account_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
