# Generated by Django 5.0.6 on 2024-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0005_remove_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.JSONField(),
        ),
    ]
