# Generated by Django 5.0.6 on 2024-08-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0006_alter_users_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermissions',
            old_name='is_add',
            new_name='is_permission',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='is_edit',
        ),
        migrations.RemoveField(
            model_name='userpermissions',
            name='is_view',
        ),
        migrations.CreateModel(
            name='ModuleUrls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserServices.modules')),
            ],
        ),
    ]
