version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./Backend/EcommerceInventory:/code
      - ./Frontend/ecommerce_inventory/build:/code/static  # Assuming React build output is in /code/static
    ports:
      - "80:80"
    environment:
      - DEBUG=0  # Set DEBUG to 0 for production-like environments
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password

volumes:
  db_data:
