# Generated by Django 5.0.6 on 2024-05-16 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InventoryServices', '0001_initial'),
        ('OrderService', '0001_initial'),
        ('ProductServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id_inventory', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_id_inventory', to='OrderService.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_id_inventory', to='OrderService.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_inwarded_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item_inwarded_item_id_inventory', to='OrderService.purchaseorderiteminwardedlog'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_inventory_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_id_inventory_log', to='InventoryServices.inventory'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_inventory_log', to='OrderService.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='so_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_id_inventory_log', to='OrderService.salesorder'),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_rack_shelf_floor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory_log', to='InventoryServices.rackandshelvesandfloor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_shelf_floor_id_inventory', to='InventoryServices.rackandshelvesandfloor'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_by_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_warhouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rackandshelvesandfloor',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_rack_shelf_floor', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory_log', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_id_inventory', to='InventoryServices.warehouse'),
        ),
    ]
