# Generated by Django 5.0.6 on 2024-08-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderService', '0003_alter_purchaseorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitems',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_id_purchase_order_items', to='OrderService.purchaseorder'),
        ),
    ]
