# Generated by Django 5.0.6 on 2024-05-18 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
