# Generated by Django 5.0.6 on 2024-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0004_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
