# Generated by Django 5.0.6 on 2024-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductServices', '0005_alter_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.FloatField(default=0),
        ),
    ]
